version: 2.1

orbs:
  python: circleci/python@2.1.1
  codecov: codecov/codecov@3.2.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: flake8
          name: Lint
      - run:
          command: coverage run -m runner
          name: Test
      - run:
          command: coverage xml -o /tmp/coverage.xml
          name: Prepare coverage results
      - store_artifacts:
          path: /tmp/coverage.xml
      - codecov/upload:
          file: /tmp/coverage.xml

workflows:
  main:
    jobs:
      - build-and-test
